name: Gromoverzhec
version: '${project.version}'
main: org.gromoverzhec.gromoverzhec.Gromoverzhec
api-version: 1.18
authors: [Filabdict]
#commands:
#  gromoverzhec_enchant:
#    permission: blacksmith