#[["Название", кол-во слотов, кол-во заблокированных слотов, 0 - если нужна привязка к нику; 1 если нет и у каждого блока свой инвентарь, вес хранилища, процент итогового веса в хранилище], ...]
chests: [
  ["§f§lПлатиновый сундук", 27, 0, 0, 50, 50],
  ["§fЖелезный сундук", 18, 0, 1, 20, 75],
  ["§6Кожаная сумка", 9, 6, 1, 5.5, 90],
]